# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-oxXlGkVvhAggeXs8rmb1jmiTut6y-be
"""

# 백준_10988
#먼저, input() 함수를 사용하여 사용자로부터 입력 문자열을 받습니다.
#입력 문자열은 str() 함수와 list() 함수를 사용하여 문자의 리스트로 변환됩니다. 이는 문자열을 반복 가능하게 만들어 역순으로 뒤집을 수 있게 합니다.
#reversed() 함수를 사용하여 문자 리스트의 순서를 반대로 바꿉니다.
#list(reversed(word))를 사용하여 새로운 리스트를 만들고 역순으로 정렬합니다.
#그런 다음 == 연산자를 사용하여 역순으로 뒤집은 리스트와 원래 리스트를 비교합니다. 이 두 리스트가 같으면, 해당 단어는 회문이라고 할 수 있습니다.
#만약 뒤집은 리스트가 원래 리스트와 같으면, 코드는 단어가 회문임을 나타내는 1을 출력합니다. 그렇지 않으면, 코드는 단어가 회문이 아니라는 것을 나타내는 0을 출력합니다.


word = list(str(input()))

if list(reversed(word)) == word:
    print(1)
else:
    print(0)